### ISSUE TITLE
App crashed unter Nexus 7 (2013) nach Scannen von Karte

### ISSUE THREAD

**Issue by crash0verride** [johnzweng/bankomatinfos#1]
Hallo,
vielen Dank für die spannende APP, leider stürzt sie auf meinem Nexus 7 Modell 2013 direkt nach dem Scannen der Karte ab, ohne Ergebnisse anzuzeigen.
Meldung: Während des Lesevorgangs ist eine "IOException" aufgetreten.

Android Version: 4.4.2

**Comment by crash0verride** [comment]
Update: App stürzt auch auf einem Nexus 5 ab, aber nur wenn bei beiden Geräten eine Raiba Bankomatkarte verwendet wird.

**Comment by johnzweng** [comment]
Danke für dein Feedback. :-)
Ja, ich kann mir schon denken, woran's liegt. Das fehlerhandling is momentan noch suboptimal und diese exception ist sogar irreführend, weils eigentlich ein Parserfehler ist. (Ich vermute dass beim Auslesen der Quickdaten was unerwartetes zurück kommt und leider bricht die app momentan in diesem Fall komplett den lesevorgang ab.)

Momentan trifft die App einfach generell sehr viele fixe Annahmen, wie die Daten auf der Karte aussehen (diese annahmen hab ich basierend auf den Ergebnissen aus meiner Karte getroffen). Ich bin ja mit der App grad mal im experimentierstadium. Ich wollte das eh noch erweitern/verbessern und weiter testen, bin aber bisher leider noch nicht dazu gekommen.

Hab leider aktuell keinen urlaub mehr und am abend finde ich momentan auch kaum zeit. Aber ich werd das bei meinen nächsten Änderungen verbessern (kann halt noch ein wenig dauern).

Danke und Lg,
Johnny :-)

**Comment by johnzweng** [comment]
Hi!
Hab jetzt das parsing in der Version 1.2.2 etwas geändert. Funktioniert es jetzt?

**Comment by crash0verride** [comment]
ich teste heute mal und meld mich, danke soweit! :-)

**Comment by crash0verride** [comment]
So jetzt schnell getestet, funktioniert jetzt ohne Probleme auf dem Nexus 7 (2013) mit Raiba Karte.

Danke für deine Bemühungen, sehr coole App um auch technisch Unversierten zu zeigen wie gefährlich solche Technologien sein können, wenn sie nicht richtig gesichert werden.

Grundsätzlich bin ich aber auch ein NFC Bankomat Zahler, ist hald einfach angenehm.

Grüße

**Comment by johnzweng** [comment]
Danke für die Rückmeldung.

Ja, ich benutze NFC Zahlungen auch gern. Zb bei den Kassen die der Zielpunkt hat, geht das ja wirklich angenehm schnell. (Bei Hofer und Spar war ich noch nicht.) Das ist ja schon sehr praktisch. Ich hab mir jetzt halt noch eine NFC Schutzhülle bestellt, aber ansonsten werd ich schon weiter NFC nutzen.

Ich wollte da nicht wirklich jemand davon abhalten. Dass das Thema in die Medien gekommen ist, war von mir nicht beabsichtigt. Wollte nur für mich rausfinden, was da alles drauf ist.
