### ISSUE TITLE
application crash in settings activity

### ISSUE THREAD

**Issue by johnzweng** [johnzweng/bankomatinfos#3]
Bug:
Application crashes when pressing the "Up" Navigation button in the Actionbar within the Settings Activity.

**Comment by alopix** [comment]
Can reproduce that.
Solution: android:parentActivityName="…" in AndroidManifest :)

**Comment by johnzweng** [comment]
Thanks. yes, I know. I just need some time for building, testing, publishing.. :-)

**Comment by johnzweng** [comment]
fixed in Version 1.2.4
