### ISSUE TITLE
Wie rufst du das Guthaben ab?

### ISSUE THREAD

**Issue by fellwell5** [johnzweng/bankomatinfos#4]
FRAGE: Wie rufst du das Guthaben ab?
Ich würde gerne eine kleine "App" mit Appinventor machen die das Guthaben per HTTP GET zu meinem Webserver übertragt der dann immer den Guthabenstand im Auge behält ;)

**Comment by johnzweng** [comment]
Hi!

Du meinst das Quick Guthaben, oder?

Dazu sende ich über NFC mit der Methode [transceive (byte[] data)](http://developer.android.com/reference/android/nfc/tech/IsoDep.html#transceive%28byte[]%29) folgende [ISO 7816-4 APDU](http://de.wikipedia.org/wiki/Application_Protocol_Data_Unit)s an die Smartcard:

<br>
**1) Auswahl der Quick Applikation auf der Karte mittels SELECT:**<br/>
_Die Applikation "Quick" hat den AID (application identifier) `D040000001000002`._

**SENDE**: `00A4040008D04000000100000200`</br>

und das sollte im OK Fall das hier zurück liefern (falls nicht, hat die Karte keine "Quick" Funktion):<br/>

**ANTWORT**: `9000`

<br>
**2) Auslesen des Files wo das Guthaben drin steht mittels READ BINARY command:**<br/>

**SENDE**: `00B0820000`</br>

das sollte im OK Fall so etwas in der Art zurückliefern:<br/>

**ANTWORT**: `0000081B9000`</br>

<br>
Die letzten beiden bytes (`90 00`) stehen wieder für OK (_"Kommando erfolgreich ausgeführt"_). Die 4 Bytes davor (`00 00 08 1B`) stellen eine Integerzahl dar, die das aktuelle Quick-Guthaben in Eurocent angibt. 

Also in diesem Beispiel:
**0000081B (hex) = 2075 (dezimal) ---> 20 Euro und 75 Cent**

Hier findest du einige allgemein nützliche Infos für die Kommunikation mit ISO 7816 SmartCards sowie Infos zum Aufbau der verwendeten Kommandos (SELECT <aid>, READ BINARY, etc..):
- [http://de.wikipedia.org/wiki/APDU](http://de.wikipedia.org/wiki/APDU)
- [http://www.cardwerk.com/smartcards/smartcard_standard_ISO7816-4_6_basic_interindustry_commands.aspx](http://www.cardwerk.com/smartcards/smartcard_standard_ISO7816-4_6_basic_interindustry_commands.aspx)
