### ISSUE TITLE
Please link to the changelog in the F-droid description

### ISSUE THREAD

**Issue by jondo** [johnzweng/bankomatinfos#6]
Do you do the F-droid releases by yourself? If yes, then please add a link to https://github.com/johnzweng/bankomatinfos/blob/master/doc/google_play_store/changelog_en.txt there, such that one can read about the changes _before_ updating.

**Comment by johnzweng** [comment]
@jondo Hi, thanks for the note. No, sorry I don't maintain the F-droid repository. But feel fre to contact the maintainer there. :)

**Comment by jondo** [comment]
I have asked for this too often, so I just filed [Please add a "changelog link" field to the database](https://gitlab.com/fdroid/fdroiddata/issues/113) to F-Droid.
