### ISSUE TITLE
Package Id changed?

### ISSUE THREAD

**Issue by ghost** [johnzweng/bankomatinfos#7]
Your recent commits change the app name and package id. Is this considered a new app? I ask because the package id should never change -- even if it has spelling issues or whatever. We cannot update bankomat 1 to bankomat 2 because technically theses are considered two different apps.

**Comment by jondo** [comment]
Btw. "we" in the above description means the F-Droid team.

**Comment by johnzweng** [comment]
hi!

Thanks for your feedback (and especially thanks for your work on the f-droid repository!).
Sorry, I forgot that this may be a problem for you.

The change of the package ID was on purpose. So yes technically it is a new app, but content-wise almost nothing changed (just removed the donation dialog). The only reason for the new package ID is Google's policy regarding play store removals. I used to have a donation dialog in the app which also contained a PayPal button and I guess this was the reason why Google banned the application from their Play Store. Reading Google's support pages there is no way to re-enable the package id again in the Play Store (even if I fix the policy-violating parts in the app).

So the only way to get it into Play Store again is to publish the app under a new package id. Google states this also in their mail they sent me after blocking the app:

> This particular app has been disabled as a policy strike. If your developer account is still in good standing, you may revise and upload a policy compliant version of this application as a new package name.

Only for this reason I changed the package id. 

I don't know how this handled in best way for F-Droid. Maybe we also publish it there as a new app?
What do you think is the best way to proceed?

**Comment by ghost** [comment]
Here is my plan: Try to have to build this version with the old package id, forced on our side. Add a note to the description that development will continue in the new app/id. Build the new app.. wait some time, phase out the old. Unfortunately, we cannot communicated directly with users that have the old build installed :/

**Comment by johnzweng** [comment]
hi, @krt16s!

I just saw your response. Would it be easier for you if I create an additional branch "fdroid-phase-out" here in my repo, using the old package id and displaying a message at application startup describing that the user should switch to the new app?

**Comment by ghost** [comment]
Well, it would sure be better, I don't know if its worth the extra effort though.. it's up to you to decided.

... in the meantime I added a new app with the latest version.

**Comment by johnzweng** [comment]
@krt16s @jondo Thanks for all your work with F-Droid! :-)

Here you go, a new branch, based on the last version with the old package id (v1.2.6), which displays a dialog window on startup which tries to explains that the app needs to be uninstalled and installed again under the new name:

https://github.com/johnzweng/bankomatinfos/tree/fdroid-phase-out

Hope this works for you. :-)

**Comment by ghost** [comment]
We should definitely have a better way to handle id or signing key changes on our own.. sigh.. for now, thanks for your (extra) work :)

**Comment by johnzweng** [comment]
@krt16s You are great! Thanks for all your efforts! :-)
